<?php

class ETC_CmsFancyBox_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_fancy_box';
    protected $title = 'Fancy Box';
    protected $icon = 'eicon-icon-box';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/perevozki\/wp-content\/themes\/equita\/elementor\/templates\/widgets\/cms_fancy_box\/layout-image\/layout1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/perevozki\/wp-content\/themes\/equita\/elementor\/templates\/widgets\/cms_fancy_box\/layout-image\/layout2.jpg"},"3":{"label":"Layout 3","image":"http:\/\/perevozki\/wp-content\/themes\/equita\/elementor\/templates\/widgets\/cms_fancy_box\/layout-image\/layout3.jpg"},"4":{"label":"Layout 4","image":"http:\/\/perevozki\/wp-content\/themes\/equita\/elementor\/templates\/widgets\/cms_fancy_box\/layout-image\/layout4.jpg"}}}]},{"name":"icon_section","label":"Box Settings","tab":"content","controls":[{"name":"selected_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"fas fa-star","library":"fa-solid"},"condition":{"layout":"3"}},{"name":"title_text","label":"Title","type":"textarea","default":"This is the heading","placeholder":"Enter your title","rows":4,"show_label":false},{"name":"description_text","label":"Description","type":"textarea","default":"Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.","placeholder":"Enter your description","rows":10,"show_label":false},{"name":"button_text","label":"Button Text","type":"text","default":"","condition":{"layout!":["3","4"]}},{"name":"link","label":"Link","type":"url"},{"name":"bg_image","label":"Background Image","type":"media","label_block":true,"condition":{"layout":"2"}},{"name":"style","label":"Style","type":"select","default":"default","options":{"default":"Default","white":"White"},"condition":{"layout":"2"}},{"name":"fancy_top_space","label":"Top Spacing","type":"slider","control_type":"responsive","condition":{"layout":"2"},"size_units":["px"],"range":{"px":{"min":0,"max":100}},"selectors":{"{{WRAPPER}} .cms-fancy-box-layout2":"padding-top: {{SIZE}}{{UNIT}};"}},{"name":"fancy_bottom_space","label":"Bottom Spacing","type":"slider","control_type":"responsive","condition":{"layout":"2"},"size_units":["px"],"range":{"px":{"min":0,"max":100}},"selectors":{"{{WRAPPER}} .cms-fancy-box-layout2":"padding-bottom: {{SIZE}}{{UNIT}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}